config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('H', 'scroll left')
config.bind('L', 'scroll right')
config.bind('<Backspace>', 'back')
config.bind('h', 'back')
config.bind('l', 'forward')
config.bind('i', 'hint inputs --first')
config.bind('gi', 'enter-mode mode ')
config.bind('m', 'spawn --userscript ~/config/scripts/mpv.sh')
config.bind('M', 'hint links spawn --userscript ~/config/scripts/mpv-hint.sh {hint-url}')

config.set('tabs.close_mouse_button', 'right')
config.set('tabs.background', True)

