config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('<Backspace>', 'back')
config.bind('i', 'hint inputs --first')
config.bind('gi', 'enter-mode mode ')
config.bind('m', 'spawn --userscript ~/config/scripts/mpv.sh')
config.bind('M', 'hint links spawn --userscript ~/config/scripts/mpv-hint.sh {hint-url}')

config.set('tabs.close_mouse_button', 'right')
config.set('tabs.background', True)
config.set('content.autoplay', False)
config.set('editor.command', ["/usr/local/Cellar/macvim/8.1-155/MacVim.app", "-g", "-f", "{file}", "-c", "normal {line}G{column0}l"])
